sudo: false
language: node_js
env:
    - NODE_ENV=development
cache:
  directories:
    - node_modules
notifications:
    email: false
node_js:
    - '5.1'
    - '4.4'
os:
  - linux
  - osx
install:
    - npm install
before_install:
    - npm i -g npm@^2.0.0
before_script:
    - npm prune
script:
    - npm test
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
